### ISSUE TITLE
Успешное завершение команды отдаёт код ошибки 1

### ISSUE THREAD

**Issue by Nitive** [rispa-io/rispa-cli#16]
Должно отдавать код 0. Кстати, я бы вообще не вызывал `process.exit` при успешном завершении скрипта

**Comment by Fyzu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [39 Улучшение информативности вывода команд cli](https://trello.com/c/Zjjztj0O/39-39-%D1%83%D0%BB%D1%83%D1%87%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%D0%B0-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4-cli)

**Comment by Fyzu** [comment]
Fixed this #19
