### ISSUE TITLE
Видение проекта

### ISSUE THREAD

**Issue by Nitive** [rispa-io/rispa-cli#28]
Решил расписать, решение каких проблем я вижу в риспе, чтобы синхронизироваться. На примере четырёх проектов.

### Небольшой проект на ванильном js
Часто хочется поэкспериментировать с чем-то, попробовать новые технологии, написать что-то небольшое. В таких случаях хочется одном командой сгенерить проект, в котором будет:

1. Сборка вебпаком
1. Транспиляция babel/typescript
1. PostCSS с автопрефиксером, опционально CSS Modules
1. Линтер
1. Тесты с Jest
1. Дев сервер

Больше ничего быть не должно, это будет только мешать. Каждый из этих пунктов должен быть отдельным плагином, и 2-6 должно быть возможно удалить/заменить. Других плагинов быть не должно. Никаких `rispa-config`, `rispa-core` и прочих неочевидных требований конфигурации. Код должен храниться отдельно от плагинов. Сейчас, по ощущениям, все плагины спаяны и отдельно работать не будут.

### Консольная утилита для ноды
В принципе, это не первоначальная цель этого проекта, но никто не мешает написать плагин, который компилит babel в отдельную папку и умеет запускать тесты.

### Средний проект на React стеке
Это единственный пункт, который сейчас более/менее реализован. Ставишь пачку плагинов, получаешь настроенный серверный рендеринг, redux, redux-loop, hot module replacement и всё остальное, а так же жёсткую привязку к технологиями. Поменять, скажем, redux-loop на redux-saga получится только форкая плагин, это не очень хорошо. Кажется, что связки технологий должны быть отдельными библиотеками, а не плагинами для риспы.

### Средний проект на кастомном стеке
Для такие проектов стартуешь на первом варианте и постепенно дописываешь плагины под потребности. Кодогенерацию, тонкую настройку вебпака, собственные правила линтинга. Потом часть этих написанных плагинов можно будет использовать под другие проекты. Идеально для большого проекта, состоящего из более мелких.

### Итог
В целом примерно такое видение — риспа должна предоставлять блоки конфигурации, из которых можно собрать проект под потребности. Плюс предоставлять какие-то утилиты, типа дев сервера. `packages/` должны быть скрыты и использоваться только при разработке плагинов.

**Comment by Laiff** [comment]
Если собирать слишком много задач, которые потенциально может решать данный проект, то получится огромное количество плагинов которое будут слабо коррелировать между собой, поэтому  мое видение это проект который облегчает жизнь именно в разработке фронта и возможно серверной части в отношении апи, просто городить на риспе cli это перебор имхо, вполне достаточно обычной структуры аля, как у нас сейчас создается для rispa-cli.

Средний проект на стеке реакта да это первая имплементация того что по существу является текущей потребностью, поэтому этот стек и был реализован в первую очередь, да не везде это сделано универсально в угоду скорости получения готового продукта, однако в дальнейшем хочется впилить сюда работу как с ангуляром так и например vue. 

Теперь относительно технологий по реакт стеку, тут тоже не все просто, есть мнение подключить использование mobx и других вещей, поэтому будет переработана ораганизация зависимостей между модулями и формирование клиентского серверного рендеров, для обеспечения заменяемости слоя предоставления данных.

Исходя из всего вышесказанного получается, определить полноценный набор плагинов будет проблематично, поэтому мы сделаем несколько пресетов, готовых для конкретных задач, указываешь что-то типа `ris new good-project --preset=react,redux,ssr` и все весь набор плагинов определен.

Теперь относительно скрытия модулей, естественно рядовые разработчики не должны видеть все модули которыми пользуется приложение, поэтому в проекте останутся только те модули которые предполагают изменение, а те что используется просто по факту наличия будут опубликованы в npm, при этом конечно остается возможность напрямую добавить их в проект и кастомизировать по необходимости.

**Comment by Nitive** [comment]
Зачем нужные плагины, предполагающие их изменения? Так же их нельзя будет обновлять, теряется вся суть плагина

**Comment by Laiff** [comment]
Расшифруй более предметно что ты имеешь ввиду?

**Comment by Nitive** [comment]
@Laiff скажим, плагин rispa-client. Подразумевается, что он установится, оттуда удалится папка `.git/`, создастся отдельный репозиторий и дальше код приложения будет писаться внутри этого плагина?

**Comment by Laiff** [comment]
Совершенно нет, фактически мы уже пришли к тому что плагин `@risp/client` может стоять как зависимость npm и ставиться оттуда, в обычной ситуации он не предполагает изменений. Однако если необходимо как то расширить данный плагин, он ставиться в нутрь проекта как сабтри с сохранением истории и возможностью обновления из апстрима

**Comment by Laiff** [comment]
New specification of plugins are implemented, close this one
