### ISSUE TITLE
Can't add plugins when select from list

### ISSUE THREAD

**Issue by wuzyk** [rispa-io/rispa-cli#32]
Steps:
1. type `ris add`
2. select any plugins from list
3. get the error
![20170627112832](https://user-images.githubusercontent.com/1822939/27573538-c773d1e2-5b2b-11e7-960b-250e32bd7af9.png)

**Comment by Laiff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve rispa-cli#32](https://trello.com/c/u53Nrj3U/47-resolve-rispa-cli32)

**Comment by Fyzu** [comment]
Fixed #34
