### ISSUE TITLE
Command hangs on bootstraping if there're unknown dependencies in installed plugins

### ISSUE THREAD

**Issue by wuzyk** [rispa-io/rispa-cli#40]
Rispa use `lerna bootstrap` for installing deps for plugins. If yarn is used as an npm-client it asks to choose dependency's version if there is no version specified in package.json found, so `lerna` hangs on this prompt.
There is an issue for lerna https://github.com/lerna/lerna/issues/863 and PR https://github.com/lerna/lerna/pull/897

**Comment by Laiff** [comment]
Resolved via #57
