### ISSUE TITLE
Unexpected error if run `ris` outside rispa project

### ISSUE THREAD

**Issue by wuzyk** [rispa-io/rispa-cli#41]
Steps to reproduce:
1. Run `ris` anywhere there is no rispa.json
2. Get the error 
![20170629104716](https://user-images.githubusercontent.com/1822939/27673144-8712347a-5cb8-11e7-997c-9699fdb8e5f5.png)

**Comment by Fyzu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [53. Resolve rispa-cli#41](https://trello.com/c/805ocln9/53-53-resolve-rispa-cli41)

**Comment by Laiff** [comment]
Resolved via #42
