### ISSUE TITLE
Plugins development docs

### ISSUE THREAD

**Issue by PFight** [rispa-io/rispa-cli#81]
I quickly looked at site, presentation and github, and cant find docs for writing my own plugins. Also, I can't find out, how all this stuff works. Is there some docs, describing internals and instructions, how to implement own templates and plugins?

**Comment by Laiff** [comment]
We had plugin specification at this time, you can find it here https://github.com/rispa-io/rispa-core/blob/master/plugin-spec.md
Also we paln write explained documentation and how to write a plugins
